# Generated by Django 4.2 on 2023-04-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='senha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
