# Generated by Django 4.2 on 2023-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_evento_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='palestrante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
