# Generated by Django 4.2 on 2023-04-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_alter_pergunta_palestrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evento.evento'),
        ),
    ]
