# Generated by Django 4.2 on 2023-04-21 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_alter_evento_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento'),
        ),
    ]
