# Generated by Django 4.2 on 2023-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_alter_palestrante_evento_alter_pergunta_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
