# Generated by Django 4.2 on 2023-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_alter_evento_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='senha',
            new_name='pin',
        ),
        migrations.AlterField(
            model_name='evento',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
