# Generated by Django 4.2 on 2023-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0012_alter_evento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pin',
            field=models.IntegerField(default=14788, help_text='O pin sera gerado automaticamente.', unique=True),
        ),
    ]
