# Generated by Django 4.2 on 2023-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_alter_evento_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pin',
            field=models.IntegerField(help_text='O pin sera gerado automaticamente.', unique=True),
        ),
    ]
