# Generated by Django 4.2 on 2023-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_alter_evento_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
