# Generated by Django 4.2 on 2023-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0015_alter_evento_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pin',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
