# Generated by Django 4.2 on 2023-04-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('evento', '0016_alter_evento_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
