# Generated by Django 4.2 on 2023-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_evento_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='filtro',
            field=models.BooleanField(default=False),
        ),
    ]
